import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import TopProgressBar from "@/components/TopProgressBar";
import { toggleDarkMode } from "@/utils/theme-toggle";
import DarkModeButton from "@/components/DMButton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen bg-gradient-blue-red`}
      >
        <DarkModeButton></DarkModeButton>
        <TopProgressBar />
        {children}
      </body>
    </html>
  );
}
